services:
  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - mode: ingress
        target: 3000
        published: 3000
    environment:
      - REDIS_HOST=reddit
      - REDIS_PORT=6379
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "127.0.0.1:3000"]
      interval: 10s
      timeout: 2s
      retries: 3
    depends_on:
      - redis
  
  processor:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 2
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PROCESSOR=true
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "127.0.0.1:3000"]
      interval: 10s
      timeout: 2s
      retries: 3
    depends_on:
      - redis

  redis:
    image: redis:alpine
    x-defang-redis: true
    ports:
      - mode: host
        target: 6379
        published: 6379